// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5mb7h_i1VWawQpJru9C25LCsYV8gy3LA',
    appId: '1:935587796527:web:095c6130fe7d22347698da',
    messagingSenderId: '935587796527',
    projectId: 'tasks-8fb3f',
    authDomain: 'tasks-8fb3f.firebaseapp.com',
    storageBucket: 'tasks-8fb3f.firebasestorage.app',
    measurementId: 'G-1D7Y3R01Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhcFdVnvAFl7em0K-60nZOVVmiB2hdgKs',
    appId: '1:935587796527:android:958efcbb1e6a16af7698da',
    messagingSenderId: '935587796527',
    projectId: 'tasks-8fb3f',
    storageBucket: 'tasks-8fb3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHza-sdukqigJJKM83IXGqygLoDSCnn2M',
    appId: '1:935587796527:ios:8372b565044de1417698da',
    messagingSenderId: '935587796527',
    projectId: 'tasks-8fb3f',
    storageBucket: 'tasks-8fb3f.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHza-sdukqigJJKM83IXGqygLoDSCnn2M',
    appId: '1:935587796527:ios:8372b565044de1417698da',
    messagingSenderId: '935587796527',
    projectId: 'tasks-8fb3f',
    storageBucket: 'tasks-8fb3f.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5mb7h_i1VWawQpJru9C25LCsYV8gy3LA',
    appId: '1:935587796527:web:de2b86209c6df7f97698da',
    messagingSenderId: '935587796527',
    projectId: 'tasks-8fb3f',
    authDomain: 'tasks-8fb3f.firebaseapp.com',
    storageBucket: 'tasks-8fb3f.firebasestorage.app',
    measurementId: 'G-QL52TXVW60',
  );
}
